# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Fengshui'
  app.identifier = 'com.livecode.testprofile2.HelloWorld'
  app.info_plist['UIStatusBarHidden'] = true
  app.info_plist['NSCameraUsageDescription'] = 'This app uses camera'
  app.info_plist['NSPhotoLibraryUsageDescription'] = 'This app uses Photo Library'
end
